### ISSUE TITLE
Bug: Problems with EntityArmorStand in Minecraft 1.14+ 

### ISSUE THREAD

**Issue by DeveloperTK** [PierreSchwang/Spigot-Lib#12]
EntityArmorStand is apparently missing the `setGravity` and `setCustomName` methods in API Version 1.14+

Stack trace on loading the plugin:
```
[21:17:55 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.EntityArmorStand.setGravity(boolean)
[21:17:55 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.nms.NmsHelper.getMethod(NmsHelper.java:99)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.nms.CraftEntity.<init>(CraftEntity.java:15)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.nms.NmsHelper.<clinit>(NmsHelper.java:15)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.internal.interceptors.PacketPlayInSettingsInterceptor.<init>(PacketPlayInSettingsInterceptor.java:22)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.AbstractJavaPlugin.onEnable(AbstractJavaPlugin.java:37)
[21:17:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:17:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:17:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:884)
[21:17:55 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:654)
[21:17:55 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[21:17:55 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[21:17:55 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:17:55 WARN]: java.lang.NoSuchMethodException: net.minecraft.server.v1_15_R1.EntityArmorStand.setCustomName(java.lang.String)
[21:17:55 WARN]:        at java.lang.Class.getMethod(Class.java:1786)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.nms.NmsHelper.getMethod(NmsHelper.java:99)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.nms.CraftEntity.<init>(CraftEntity.java:18)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.nms.NmsHelper.<clinit>(NmsHelper.java:15)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.internal.interceptors.PacketPlayInSettingsInterceptor.<init>(PacketPlayInSettingsInterceptor.java:22)
[21:17:55 WARN]:        at de.pierreschwang.spigotlib.AbstractJavaPlugin.onEnable(AbstractJavaPlugin.java:37)
[21:17:55 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:17:55 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:17:55 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:884)
[21:17:55 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:654)
[21:17:55 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[21:17:55 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
[21:17:55 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[21:17:55 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[21:17:55 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by PierreSchwang** [comment]
Hi!

Yes, there are some issues with Bukkit 1.9+ including Sounds and Features. This is because of API changes in these versions.
I've planned to implement support for a wider collection of versions, but this may take a while.

Best regards

**Comment by DeveloperTK** [comment]
Bump... Still not optimized für 1.9+ :(((
