### ISSUE TITLE
Problems with scoreboard in newer versions

### ISSUE THREAD

**Issue by DeveloperTK** [PierreSchwang/Spigot-Lib#13]
An event registered by SpigotLib throws a NullPointerException every time a player disconnects. This ocurred to me in minecraft versions 1.14 - 1.16. Here is the stack trace:

```
[09:41:30 INFO]: [player] lost connection: Disconnected
[09:41:30 ERROR]: Could not pass event PlayerQuitEvent to [plugin using SpigotLib]
java.lang.NullPointerException: null
        at [plugin main class]$1.lambda$getPrefix$0([plugin main class]) ~[?:?]
        at de.pierreschwang.spigotlib.scoreboard.InternalScoreboard.refresh(InternalScoreboard.java:45) ~[?:?]
        at de.pierreschwang.spigotlib.scoreboard.AbstractScoreboard.lambda$refresh$0(AbstractScoreboard.java:38) ~[?:?]
        at java.util.HashMap$Values.forEach(HashMap.java:976) ~[?:?]
        at de.pierreschwang.spigotlib.scoreboard.AbstractScoreboard.refresh(AbstractScoreboard.java:38) ~[?:?]
        at de.pierreschwang.spigotlib.internal.PlayerListener.onPlayerQuit(PlayerListener.java:46) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.1.jar:git-Paper-27]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.1.jar:git-Paper-27]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.1.jar:git-Paper-27]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.PlayerList.disconnect(PlayerList.java:498) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.PlayerConnection.a(PlayerConnection.java:1590) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.NetworkManager.handleDisconnection(NetworkManager.java:481) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.ServerConnection.c(ServerConnection.java:162) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1378) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[patched_1.16.1.jar:git-Paper-27]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-27]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
The getPrefix() function of getPlayerRenderer() contains this:
```
public Function<User, String> getPrefix() {
      return user -> getPlayerRole(user.getPlayer().getUniqueId());
}
```
I have an idea what could be wrong: Is the `User` object null or does it return null for the `getPlayer()` method? This error only comes up on my live server and I am unable to reproduce this problem in a testing envoronment...

**Comment by PierreSchwang** [comment]
Hi,

could you please provide me your source code or jar so that I can reproduce the error?

**Comment by PierreSchwang** [comment]
The problem should be solved now - Could you please recompile your plugin with the newest spigot lib version and tell me if the exception is still thrown?

**Comment by DeveloperTK** [comment]
Yes, 7d157d020409f6c9568138f508ff2ddfecbb5143 solved the problem. Thanks!
