### ISSUE TITLE
LanguageHandler#getLanguageTemplateDir

### ISSUE THREAD

**Issue by test-nk** [PierreSchwang/Spigot-Lib#16]
I'm modifieng the LanguageHandler so that the language files aren't in the datafolder. Instead they are in a normal folder on the server (e.g. /home/languages). So I have to modify getLanguageTemplateDir in the LanguageHandler too, but what do I have to enter in the path (fileSystem.getPath())?

**Comment by PierreSchwang** [comment]
Hi,

I guess you are editing / forking the library. You have to change this line:
https://github.com/PierreSchwang/Spigot-Lib/blob/4ddd5eba4f42b1a66ae0a52f083764050253ef52/src/main/java/de/pierreschwang/spigotlib/lang/LanguageHandler.java#L24
to for example `final File languageFolder = new File("/home/languages");`

The copyFromResources-Method is for template-files which should be copied to the languageFolder (These templates are stored inside of the jar). So, I guess this should be regardless anyway.

If you have any further questions, feel free to ask :)

**Comment by test-nk** [comment]
Hi @PierreSchwang,

thank you very much, this helped! So I have to remove the copyFromResources and getLanguageTemplateDir method? But if I remove them, the locales won't be synchronized with the files if there are any changes

**Comment by PierreSchwang** [comment]
Oh yeah, then just change the mentioned line in the LanguageHandler.java - You should be good to go with that.

**Comment by test-nk** [comment]
in the init of the LanguageHandler occures an error because it can't find /lang if I only change the mentioned line

**Comment by PierreSchwang** [comment]
Could you share the full stacktrace? And does the folder have the correct permission, so that the server can access the folder?

**Comment by test-nk** [comment]
@PierreSchwang  The folder has root permissions
```
[23:31:55] [Server thread/WARN]: java.nio.file.NoSuchFileException: /lang
[23:31:55] [Server thread/WARN]: 	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666)
[23:31:55] [Server thread/WARN]: 	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
[23:31:55] [Server thread/WARN]: 	at java.nio.file.Files.readAttributes(Files.java:1737)
[23:31:55] [Server thread/WARN]: 	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
[23:31:55] [Server thread/WARN]: 	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
[23:31:55] [Server thread/WARN]: 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
[23:31:55] [Server thread/WARN]: 	at java.nio.file.Files.walkFileTree(Files.java:2662)
[23:31:55] [Server thread/WARN]: 	at java.nio.file.Files.walkFileTree(Files.java:2742)
[23:31:55] [Server thread/WARN]: 	at [package].LanguageHandler.copyFromResources(LanguageHandler.java:63)
[23:31:55] [Server thread/WARN]: 	at [package].LanguageHandler.<init>(LanguageHandler.java:32)
[23:31:55] [Server thread/WARN]: 	at [package].onPluginEnable([Class].java:89)
[23:31:55] [Server thread/WARN]: 	at [package].onEnable([Class].java:32)
[23:31:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[23:31:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[23:31:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[23:31:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[23:31:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[23:31:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by test-nk** [comment]
@PierreSchwang

**Comment by PierreSchwang** [comment]
> 
> 
> @PierreSchwang The folder has root permissions
> 
> ```
> [23:31:55] [Server thread/WARN]: java.nio.file.NoSuchFileException: /lang
> [23:31:55] [Server thread/WARN]: 	at com.sun.nio.zipfs.ZipPath.getAttributes(ZipPath.java:666)
> [23:31:55] [Server thread/WARN]: 	at com.sun.nio.zipfs.ZipFileSystemProvider.readAttributes(ZipFileSystemProvider.java:294)
> [23:31:55] [Server thread/WARN]: 	at java.nio.file.Files.readAttributes(Files.java:1737)
> [23:31:55] [Server thread/WARN]: 	at java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
> [23:31:55] [Server thread/WARN]: 	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
> [23:31:55] [Server thread/WARN]: 	at java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
> [23:31:55] [Server thread/WARN]: 	at java.nio.file.Files.walkFileTree(Files.java:2662)
> [23:31:55] [Server thread/WARN]: 	at java.nio.file.Files.walkFileTree(Files.java:2742)
> [23:31:55] [Server thread/WARN]: 	at [package].LanguageHandler.copyFromResources(LanguageHandler.java:63)
> [23:31:55] [Server thread/WARN]: 	at [package].LanguageHandler.<init>(LanguageHandler.java:32)
> [23:31:55] [Server thread/WARN]: 	at [package].onPluginEnable([Class].java:89)
> [23:31:55] [Server thread/WARN]: 	at [package].onEnable([Class].java:32)
> [23:31:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
> [23:31:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
> [23:31:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
> [23:31:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
> [23:31:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
> [23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
> [23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
> [23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
> [23:31:55] [Server thread/WARN]: 	at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
> [23:31:55] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
> ```

Does your server also run as root?
